### ISSUE TITLE
Add camera controllers

### ISSUE THREAD

**Issue by andeplane** [ovilab/atomify-lammps#48]
Implementationwise, we will use one controller with flymode navigation as a mode.
- [x] Add single QML controller
- [x] Add flymode mode
- [x] Add c++ class that handles mouse move in flymode navigation
- [x] Add shortcut / icon in GUI
- [x] Tune parameters so it feels right

Henrik Sveinsson said it felt weird that flymode navigation moves trackball viewcenter. I think I agree. We should consider having two different cameras (basically storing viewcenter, position and upvector for both cameras).

**Comment by andeplane** [comment]
We want to have both flymode navigation and trackball navigation.

**Comment by andeplane** [comment]
Added flymode in 3dff2138d49f556ffcea0e2070deb15a29bc4c31

**Comment by dragly** [comment]
Use two cameras, one for flymode and one for trackball. One shortcut to spawn flymode from current trackball and one shortcut to jump to previous flymode position.

In the long term, support multiple cameras and viewports. One trackball and one flymode camera per viewport.
